sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: h6ObiU4CzLx291askZ/UuUehbPXGOasRAbyMERrMYyHD5rQ9Shig392ic1CKpqfEH03RlDz/we3a6RRfH1zduItNUnSVtvWTfu/U8f8OzXqo1YLmJQk/XezfDEcQuIHpZCMkiwXiPg74xrqkr61OmSwucHCkfgpoEbS7iBIlsGYzTa7VOZzKLXLVQuG21f6xKZwtut1fv2wvAwksDH3C6poT6c8rXtIDikHEz/g5Y+Qb02Xkk8Undj1WfzFJViTKEz26n0fwVaEf1RWXEzl2ZEW2nisjcfCalwuKZHl0GXUhgRpZNpyV4nN3YTTg6imzKqvYSP2widsi8FXSv1zCa3dxAMOswUECJ8DR8yCdS58qsOZ97tqdsbdyQZ0ld2QmVAI5s9zxsUdRUTk6U+5sUaB1BUCLtUjIqVyl/LcT8kEZAxg2nZkb/aUPk7Q4VFbxjMR5P0sK4wAR4I9QZodPVkqzajhbC86WaMLIm05wJh66V8vIgorwmWoQDUkZr1cCoy5MJgvsWHRruZmcSouJaQ4iP3FgVFBUXQw2NUIksgWDXwMVba0dnOK+nB9pWYw7ktYmgDaQEHVNcc7vOTGyfxZ8lQtxZHNK0eFmIi0sDxssLI03caKg3hy6RqD+I/5zsggzbo+v/nSj/J3CyhbnNUk4zdP7kkfR2KsXsGDOT1Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Taming-of-the-Shrew_1772
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy